language: python
python:
  - "3.6"

services:
  - docker

before_install:
  - pip install docker-compose

script:
  - docker-compose run --rm app sh -c "pytest && flake8"
  - docker-compose run app sh -c "rm -rf .pytest_cache/"
  - docker-compose run app sh -c "rm -rf __pycache__/"

deploy:
  provider: script
  script: bash deploy
  on:
    branch: master